version: '3'

services:
  django:
    container_name: product_app
    build: product_project/
    environment:
      DJANGO_SUPERUSER_USERNAME: some_username
      DJANGO_SUPERUSER_PASSWORD: some_password
      DJANGO_SUPERUSER_EMAIL: some_email@gmail.com
      CELERY_BROKER: redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
      - redis

  postgresql:
    container_name: product_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: some_password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      retries: 5
      timeout: 5s

  redis:
    container_name: product_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      retries: 5
      timeout: 5s

  celery:
    build: product_project/
    command: celery -A product_project worker -l INFO
    depends_on:
      - django
      - redis
