version: '3'

services:
  django:
    container_name: product_app
    build: product_project/
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
      - redis


  postgresql:
    container_name: product_db
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      retries: 5
      timeout: 5s

  redis:
    container_name: product_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      retries: 5
      timeout: 5s

  celery:
    build: product_project/
    command: celery -A product_project worker -l INFO
    env_file:
      - .env
    depends_on:
      - django
      - redis
